version: '3'

services:
  jekyll:
    container_name: pix-engineering
    image: jekyll/jekyll:latest
    command: bash -c "bundle install && bundle exec jekyll serve --watch --force_polling --verbose -H 0.0.0.0"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
